[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
